### PR TITLE
add data models

### PR DESCRIPTION
**Pull request by ReemMohamedAbdelfatah**
Hello Microverse! In this PR the followings are done:

- [x] Create a new app. Give it a meaningful name.

- [x] Initialize  project with Git.

- [x]  project has Postgres database set up.

- [x] Build your project schema.

- [x] Create and run the necessary migration files.

- [x] Table and column names should match the ERD diagram.

- [x] photo for users table should be a link to an image

- [x] Foreign keys should be included.

- [x] In posts table the column holding the foreign key to the users table should be named author_id

- [x] All columns that are foreign keys should have a corresponding index.

### CODE REVIEW

**Review by Gambit142 — COMMENTED** [review]
Hi @ReemMohamedAbdelfatah 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Kindly make the following changes to the README file given to you:
  - Please remove the Microverse link or replace yours with it 
  - Kindly remove the Entire Live Demo Section link
  - The FAQ section is optional. You can decide to remove it or fill that section with the appropriate information
  - The link to your MIT LICENSE is broken. Kindly fix it. 👍 
  
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by mwanawabangona — APPROVED** [review]
Hi @ReemMohamedAbdelfatah,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  


## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job getting approved on your first try!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ReemMohamedAbdelfatah** [comment]
Thank you! @mwanawabangona

**Review by IngDavidTM — COMMENTED** [review]
Hi @ReemMohamedAbdelfatah 🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
